name: Publish npm package

on:
    push:
        branches:
            - release/*/*
jobs:
    publish:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3
            - name: Publish a npm package
              uses: valu-digital/npm-packages/.github/release-action@master
              with:
                  npm_token: "${{ secrets.NPM_TOKEN }}"
